// catalog-ui/src/app/ng2/components/ui/tabs/tabs.component.ts
/*-
 * ============LICENSE_START=======================================================
 * SDC
 * ================================================================================
 * Copyright (C) 2017 AT&T Intellectual Property. All rights reserved.
 * ================================================================================
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ============LICENSE_END=========================================================
 */

import { Component, ContentChildren, QueryList, AfterContentInit, Input, Output, EventEmitter } from '@angular/core';
import { Tab } from './tab/tab.component';
import { ViewEncapsulation } from '@angular/core';
import { trigger, state, style, transition, animate, keyframes } from '@angular/core';

export {Tab};

@Component({
    selector: 'tabs',
    templateUrl: './tabs.component.html',
    styleUrls: ['./tabs.component.less'],
    encapsulation: ViewEncapsulation.None,
    animations: [
        trigger('indicatorAnimation', [
            transition(':enter', [style({ transform: 'translateY(-50%)', opacity: 0 }), animate('250ms', style({ transform: 'translateY(0)', opacity: 1 })) ]),
            transition(':leave', [style({ opacity: 1 }), animate('500ms', style({ opacity: 0 })) ])
        ])
    ]
})
export class Tabs implements AfterContentInit {

    @Input() tabStyle: string;
    @Input() hideIndicationOnTabChange?: boolean = false;
    @ContentChildren(Tab) tabs: QueryList<Tab>;
    @Output() tabChanged: EventEmitter<Tab> = new EventEmitter<Tab>();


    ngAfterContentInit() {  
        //after contentChildren are set, determine active tab. If no active tab set, activate the first one
        let activeTabs = this.tabs.filter((tab) => tab.active);
 
        if (activeTabs.length === 0) {
            this.selectTab(this.tabs.first);
        }
    }

    selectTab(tab: Tab) {
        //activate the tab the user clicked.
        this.tabs.toArray().forEach(tab => {
            tab.active = false;
            if (this.hideIndicationOnTabChange && tab.indication) {
                tab.indication = null;
            }
        });
        tab.active = true;
        this.tabChanged.emit(tab);
    }

    triggerTabChange(tabTitle) {
        this.tabs.toArray().forEach(tab => {
            tab.active = (tab.title == tabTitle) ? true : false;
        });
    }

    setTabIndication(tabTitle:string, indication?:number) {
        let selectedTab: Tab = this.tabs.toArray().find(tab => tab.title == tabTitle);
        selectedTab.indication = indication || null;
    }

}

<!--
  ~ Copyright (C) 2018 AT&T Intellectual Property. All rights reserved.
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~      http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<div class="tabs {{tabStyle}}">
<ng-container *ngFor="let tab of tabs">
    <div class="tab" *ngIf="tab.show" (click)="selectTab(tab)" [class.active]="tab.active" [attr.data-tests-id]="tab.title" [ngStyle]="{'color': tab.highlight}">
        {{tab.title}}
        <div class="tab-indication" *ngIf="tab.indication" [@indicatorAnimation]="tab.indication">{{tab.indication}}</div>
    </div>
</ng-container>
</div>
<div class="tab-content-container">
    <ng-content></ng-content>
</div>

// openecomp-ui/src/nfvo-components/input/validation/Tabs.jsx
/*!
 * Copyright (C) 2017 AT&T Intellectual Property. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */
import React from 'react';
import ReactDOM from 'react-dom';
import {default as SDCTabs} from 'sdc-ui/lib/react/Tabs.js';
import Overlay from 'react-bootstrap/lib/Overlay.js';
import Tooltip from 'react-bootstrap/lib/Tooltip.js';

import i18n from 'nfvo-utils/i18n/i18n.js';

export default
class Tabs extends React.Component {

	static propTypes = {
		children: React.PropTypes.node
	};

	cloneTab(element) {
		const {invalidTabs} = this.props;
		return React.cloneElement(
			element,
			{
				key: element.props.tabId,
				className: invalidTabs.indexOf(element.props.tabId) > -1 ? 'invalid-tab' : 'valid-tab'
			}
		);
	}

	showTabsError() {
		const {invalidTabs} = this.props;
		const showError = ((invalidTabs.length === 1 && invalidTabs[0] !== this.props.activeTab) || (invalidTabs.length > 1));
		return showError;
	}

	render() {
		// eslint-disable-next-line no-unused-vars
		let {invalidTabs, ...tabProps} = this.props;
		return (
			<div>
				<SDCTabs {...tabProps} ref='tabsList' id='tabsList' >
					{this.props.children.map(element => this.cloneTab(element))}
				</SDCTabs>
				<Overlay
					animation={false}
					show={this.showTabsError()}
					placement='bottom'
					target={() => {
						let target = ReactDOM.findDOMNode(this.refs.tabsList).querySelector('ul > li.invalid-tab:not(.sdc-tab-active):nth-of-type(n)');
						return target && target.offsetParent ? target : undefined;
					}
					}
					container={() => {
						let target = ReactDOM.findDOMNode(this.refs.tabsList).querySelector('ul > li.invalid-tab:not(.sdc-tab-active):nth-of-type(n)');
						return target && target.offsetParent ? target.offsetParent : this;
					}}>
					<Tooltip
						id='error-some-tabs-contain-errors'
						className='validation-error-message'>
						{i18n('One or more tabs are invalid')}
					</Tooltip>
				</Overlay>
			</div>
		);
	}
}
