// catalog-ui/src/app/components/ui/modal/modal.component.ts
/*-
 * ============LICENSE_START=======================================================
 * SDC
 * ================================================================================
 * Copyright (C) 2017 AT&T Intellectual Property. All rights reserved.
 * ================================================================================
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ============LICENSE_END=========================================================
 */

/**
 * Created by rc2122 on 6/1/2017.
 */
import { Component, ElementRef, HostListener, Input, OnInit, OnDestroy } from '@angular/core';
import {ViewContainerRef, ViewChild} from '@angular/core';
import * as $ from 'jquery';
import {ButtonsModelMap} from 'app/models/button';
import {ModalModel} from 'app/models/modal';
import { FocusTrap } from 'app/shared/accessibility/focus-trap';

let modalIdCounter = 0;

@Component({
    selector: 'modal',
    templateUrl: './modal.component.html',
    styleUrls:['modal.component.less']
})

export class ModalComponent implements OnInit, OnDestroy {
    @Input() isMovable: boolean;
    @Input() input: ModalModel;
    @Input() dynamicContent: any;
    @ViewChild('dynamicContentContainer', { read: ViewContainerRef }) dynamicContentContainer: ViewContainerRef;
    modalId: number;
    private modalElement: JQuery;
    private focusTrap: FocusTrap;

    constructor( el: ElementRef ) {
        this.modalElement = $(el.nativeElement);
        this.modalId = ++modalIdCounter;
        this.focusTrap = new FocusTrap();
    }

    @HostListener('keydown', ['$event'])
    handleKeydown(event: KeyboardEvent): void {
        if (event.key === 'Escape' || event.keyCode === 27) {
            this.close();
        }
    }

    ngOnInit(): void {
        this.modalElement.appendTo('body');
    }

    ngOnDestroy(): void {
        this.focusTrap.deactivate();
        this.modalElement.remove();
    }

    open(): void {
        this.modalElement.show();
        $('body').addClass('modal-open');
        this.focusTrap.activate(this.modalElement[0] as HTMLElement);
    }

    close(): void {
        this.focusTrap.deactivate();
        this.modalElement.hide();
        $('body').removeClass('modal-open');
    }
}

// openecomp-ui/src/nfvo-components/modal/Modal.jsx
/*!
 * Copyright (C) 2017 AT&T Intellectual Property. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */
import React from 'react';
import ReactDOM from 'react-dom';
import BootstrapModal from 'react-bootstrap/lib/Modal.js';

let nextModalId = 0;

export default class Modal extends React.Component {

	static Header = BootstrapModal.Header;

	static Title = BootstrapModal.Title;

	static Footer = BootstrapModal.Footer;

	static Body = class ModalBody extends React.Component {

		render() {
			let {children, ...props} = this.props;
			return (
				<BootstrapModal.Body {...props}>
					{children}
				</BootstrapModal.Body>
			);
		}

		componentDidMount() {
			let element = ReactDOM.findDOMNode(this);
			element.addEventListener('click', event => {
				if (event.target.tagName === 'A') {
					event.preventDefault();
				}
			});
			['wheel', 'mousewheel', 'DOMMouseScroll'].forEach(eventType =>
				element.addEventListener(eventType, event => event.stopPropagation())
			);
		}
	};

	componentWillMount() {
		this.modalId = `dox-ui-modal-${nextModalId++}`;
	}

	componentDidMount() {
		this.ensureRootClass();
	}

	componentDidUpdate() {
		this.ensureRootClass();
	}

	ensureRootClass() {
		let element = document.getElementById(this.modalId);
		while(element && !element.hasAttribute('data-reactroot')) {
			element = element.parentElement;
		}
		if (element && !element.classList.contains('dox-ui')) {
			element.classList.add('dox-ui');
		}
	}

	render() {
		let {children, ...props} = this.props;
		return (
			<BootstrapModal {...props} id={this.modalId}>
				{children}
			</BootstrapModal>
		);
	}
}
